"""
常量模块：统一管理插件中使用的所有常量

本模块集中管理：
- 价格常量：MIN_PRICE, MAX_PRICE
- 时间常量：MAX_TIMESTAMP_DIFF, MAX_CALLBACK_QUEUE_SIZE
- 业务常量：MAX_SEND_FAIL_COUNT, MAX_TRIGGER_BATCH
- 重试延迟常量：RETRY_DELAY_SHORT, RETRY_DELAY_LONG
"""

from decimal import Decimal

MIN_PRICE = Decimal("500")
MAX_PRICE = Decimal("5000")

MAX_TIMESTAMP_DIFF = 60
MAX_CALLBACK_QUEUE_SIZE = 100

MAX_SEND_FAIL_COUNT = 3
MAX_TRIGGER_BATCH = 50

RETRY_DELAY_SHORT = 5
RETRY_DELAY_LONG = 30
